apiVersion: v1
kind: Service
metadata:
  name: pes2ug23cs064-service
  namespace: pes2ug23cs064-beta
spec:
  type: ClusterIP
  selector:
    app: nginx
  ports:
  - port: 80
    targetPort: 80
